name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi10/ubi-minimal
    steps:
      - name: Install dependencies
        run: microdnf -y install git-core maven-openjdk21
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Maven build
        run: mvn -V -B -Prelease -Dgpg.skip clean install
